#!/bin/bash

in_path(){
  cmd=$1  ourpath=$PATH  result=1
  oldIFS=$IFS IFS=":"

  for directory in "$ourpath"
    do 
      if [ -x $directory/$cmd ] ; then # The -x operator helps us in checking if the given file has execution permission
	       echo "current val : $directory/$cmd"
	       result=0
      fi
    done

  IFS=$oldIFS
  echo "result: $result"
  return $result
}
echo "Total args passed: $#"

if [ $# -eq 0 ]; then
  echo "Usage: $0 command" >&2
  exit 1
fi

in_path $1

echo "last foreground executed command exit code is: $?"

case $? in
	0) echo "$1 found in PATH" ;;
	1) echo "$1 NOT found in PATH" ;;
esac

exit 0

